import Link from 'next/link'
import Image from 'next/image'
import { Poppins } from 'next/font/google'
import './globals.css'

// can be used to make a component that shows up on every page of the app

export const metadata = {
  title: 'ranked',
  description: 'Generated by create next app',
}

const inter = Poppins({ 
  subsets: ['latin'],
  weight: '400'
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
        <Image
        src="/rankedlogo.png"
        width={500}
        height={500}
        alt="Picture of the author"
      />

        </nav>
        {children}
        
      </body>
    </html>
  )
}
