import NavigationBar from "./components/navigation/navbar"
import RegisterModal from "./components/modals/register-modal"
import LoginModal from "./components/modals/login-modal"
import { Poppins } from 'next/font/google'
import './globals.css'
import getCurrentUser from "./actions/getCurrentUser"
import CreateTierListModal from "./components/modals/create-list-modal"

// can be used to make a component that shows up on every page of the app

export const metadata = {
  title: 'ranked',
  description: 'Generated by create next app',
}

const inter = Poppins({ 
  subsets: ['latin'],
  weight: '400'
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const currentUser = await getCurrentUser()

  return (
    <html lang="en">
      <body className={inter.className}>
          <RegisterModal/>
          <LoginModal/>
          <CreateTierListModal/>
          <NavigationBar currentUser={currentUser}/>
        {children}
      </body>
    </html>

  )
}
